apiVersion: v1
kind: Service
metadata:
  name: svelte-frontend-service
spec:
  selector:
    app: svelte-frontend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5173
  type: LoadBalancer
